# Generated by Django 4.2.9 on 2024-01-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255)),
                ('emp_qty', models.IntegerField()),
                ('emp_exp', models.DateField()),
            ],
        ),
    ]
