# Generated by Django 4.2.9 on 2024-01-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('custom_name', models.CharField(max_length=255)),
                ('custom_lastname', models.CharField(max_length=255)),
                ('email', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
            ],
        ),
    ]
