# Generated by Django 4.2.9 on 2024-01-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
