# Generated by Django 4.2.9 on 2024-01-27 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_custom_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
