# Generated by Django 4.2.9 on 2024-01-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_job_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Typework',
            field=models.CharField(default='ค่าเริ่มต้น', max_length=255),
        ),
    ]
