# Generated by Django 4.2.9 on 2024-01-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_job_typework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Typework',
            field=models.CharField(max_length=255),
        ),
    ]
