# Generated by Django 4.2.9 on 2024-02-06 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_alter_job_typework'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company'),
        ),
    ]
