# Generated by Django 4.2.9 on 2024-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_custom_cv_file_custom_date_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='source',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='custom',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
